const Joi = require("joi");

exports.care_recipient_questionnaire_post = Joi.object({
  client_info: Joi.object({
    first_name: Joi.string().max(100).optional().allow(null),
    last_name: Joi.string().max(100).optional().allow(null),
    address: Joi.string().max(255).optional().allow(null),
    city: Joi.string().max(100).optional().allow(null),
    state: Joi.string().max(50).optional().allow(null),
    zip: Joi.string().max(20).optional().allow(null),
    ssn: Joi.string().max(20).optional().allow(null),
    date_of_birth: Joi.date().iso().optional().allow(null),
    birth_place: Joi.string().max(255).optional().allow(null),
    phone: Joi.string().max(20).optional().allow(null),
    email: Joi.string().email().optional().allow(null),
    cultural_background: Joi.string().max(255).optional().allow(null),
    education: Joi.string().max(255).optional().allow(null),
    religion: Joi.string().max(255).optional().allow(null),
    active_religion_location: Joi.string().max(255).optional().allow(null),
    marital_status: Joi.string().max(50).optional().allow(null),
    date_of_divorce_or_widowhood: Joi.date().iso().optional().allow(null),
    loss_impact_description: Joi.string().max(1000).optional().allow(null),
    dnr: Joi.string().max(255).optional().allow(null),
    preferred_hospital: Joi.string().optional().allow(null),
    trust: Joi.string().max(255).optional().allow(null),
    lifecare: Joi.string().max(255).optional().allow(null),
    will: Joi.string().max(255).optional().allow(null),
    living_will: Joi.string().max(255).optional().allow(null),
    funeral_arrangements: Joi.string().max(255).optional().allow(null),
    cemetery_plot: Joi.string().max(255).optional().allow(null),
    monthly_income: Joi.string().max(255).optional().allow(null),
    spouse_income: Joi.string().max(255).optional().allow(null),
    savings: Joi.string().max(255).optional().allow(null),
    other_assets: Joi.string().max(255).optional().allow(null),
    financial_problems_description: Joi.string().max(1000).optional().allow(null),
  }),
  insurance: Joi.object({
    medicare_a: Joi.string().max(255).optional().allow(null),
    medicare_b: Joi.string().max(255).optional().allow(null),
    medicare_numbers: Joi.string().max(255).optional().allow(null),
    supplement_plan: Joi.string().max(255).optional().allow(null),
    provider: Joi.string().max(255).optional().allow(null),
    policy_number: Joi.string().max(255).optional().allow(null),
    phone: Joi.string().max(20).optional().allow(null),
    mental_health_coverage: Joi.boolean().optional().allow(null),
    hmo: Joi.string().max(255).optional().allow(null),
    hmo_policy_number: Joi.string().max(255).optional().allow(null),
    hmo_phone: Joi.string().max(20).optional().allow(null),
    long_term_care_insurance_name: Joi.string().max(255).optional().allow(null),
    long_term_care_insurance_policy_number: Joi.string().max(255).optional().allow(null),
    long_term_care_insurance_phone: Joi.string().max(20).optional().allow(null),
  }),
  relatives: Joi.array().items(
    Joi.object({
      id: Joi.string().uuid().optional(),
      name: Joi.string().max(255).optional().allow(null),
      address: Joi.string().max(255).optional().allow(null),
      home_phone: Joi.string().max(20).optional().allow(null),
      work_phone: Joi.string().max(20).optional().allow(null),
      relationship: Joi.string().max(255).optional().allow(null),
      email: Joi.string().email().optional().allow(null),
    })
  ),
  friends_contact: Joi.array().items(
    Joi.object({
      id: Joi.string().uuid().optional(),
      name: Joi.string().max(255).optional().allow(null),
      address: Joi.string().max(255).optional().allow(null),
      relationship: Joi.string().max(255).optional().allow(null),
      phone: Joi.string().max(20).optional().allow(null),
      help_description: Joi.string().max(1000).optional().allow(null),
    })
  ),
  professional_contacts: Joi.array().items(
    Joi.object({
      id: Joi.string().uuid().optional(),
      role: Joi.string().max(255).optional().allow(null),
      name: Joi.string().max(255).optional().allow(null),
      phone: Joi.string().max(20).optional().allow(null),
    })
  ),
  healthcare_providers: Joi.array().items(
    Joi.object({
      id: Joi.string().uuid().optional(),
      provider_name: Joi.string().max(255).optional().allow(null),
      phone: Joi.string().max(20).optional().allow(null),
      for_what_problem: Joi.string().max(255).optional().allow(null),
    })
  ),
  medical_conditions: Joi.object({
    id: Joi.string().uuid().optional(),
    problem: Joi.string().max(1000).optional().allow(null),
    treatment: Joi.string().max(1000).optional().allow(null),
    medications: Joi.string().max(1000).optional().allow(null),
  }),
  medical_info: Joi.object({
    id: Joi.string().uuid().optional().allow(null),
    last_checkup_date: Joi.date().iso().optional().allow(null),
    allergies: Joi.string().max(1000).optional().allow(null),
    recent_hospitalization: Joi.boolean().optional().allow(null),
    hospital_details: Joi.string().max(1000).optional().allow(null),
    support_system_thoughts: Joi.string().max(1000).optional().allow(null),
  }),
  questionnaire: Joi.object({
    id: Joi.string().uuid().optional().allow(null),
    support_system_rating: Joi.string().max(255).optional().allow(null),
    support_system_problems: Joi.string().max(1000).optional().allow(null),
    emergency_contacts: Joi.string().max(1000).optional().allow(null),
    house_cleaning_agency: Joi.string().max(255).optional().allow(null),
    house_cleaning_satisfaction: Joi.string().max(255).optional().allow(null),
    house_cleaning_frequency: Joi.string().max(255).optional().allow(null),
    home_aid_agency: Joi.string().max(255).optional().allow(null),
    home_aid_satisfaction: Joi.string().max(255).optional().allow(null),
    home_aid_frequency: Joi.string().max(255).optional().allow(null),
    home_health_agency: Joi.string().max(255).optional().allow(null),
    home_health_satisfaction: Joi.string().max(255).optional().allow(null),
    home_health_frequency: Joi.string().max(255).optional().allow(null),
    maintenance_agency: Joi.string().max(255).optional().allow(null),
    maintenance_satisfaction: Joi.string().max(255).optional().allow(null),
    maintenance_frequency: Joi.string().max(255).optional().allow(null),
    other_help_agency: Joi.string().max(255).optional().allow(null),
    other_help_satisfaction: Joi.string().max(255).optional().allow(null),
    other_help_frequency: Joi.string().max(255).optional().allow(null),
    living_environment_type: Joi.string().max(255).optional().allow(null),
    home_environment_adequacy: Joi.string().max(255).optional().allow(null),
    problem_areas_daily_living: Joi.string().max(255).optional().allow(null),
    problem_areas_explanation: Joi.string().max(1000).optional().allow(null),
    problems_risks: Joi.string().max(1000).optional().allow(null),
    nutrition_concerns: Joi.string().max(1000).optional().allow(null),
    self_care_capacity_summary: Joi.string().max(1000).optional().allow(null),
    memory_problems: Joi.string().max(1000).optional().allow(null),
    emotional_health_notes: Joi.string().max(1000).optional().allow(null),
    personality_coping: Joi.string().max(1000).optional().allow(null),
    recent_behavior_changes: Joi.string().max(1000).optional().allow(null),
    recipient_shares_concerns: Joi.boolean().optional().allow(null),
    recipient_shares_concerns_notes: Joi.string().max(1000).optional().allow(null),
    emotional_problems_history: Joi.boolean().optional().allow(null),
    emotional_problems_treatment: Joi.boolean().optional().allow(null),
    emotional_problems_notes: Joi.string().max(1000).optional().allow(null),
    recent_losses_impact: Joi.string().max(1000).optional().allow(null),
    social_life_notes: Joi.string().max(1000).optional().allow(null),
    occupation_profession: Joi.string().max(255).optional().allow(null),
    retirement_date: Joi.date().iso().optional().allow(null),
    retirement_adjustment: Joi.string().max(1000).optional().allow(null),
    major_concerns: Joi.string().max(1000).optional().allow(null),
    areas_accepting_help: Joi.string().max(1000).optional().allow(null),
  }),
});
