const Joi = require("joi");

exports.facesheet_put = Joi.object({
  client_info: Joi.object({
    first_name: Joi.string().optional().allow(null),
    last_name: Joi.string().optional().allow(null),
    date_of_birth: Joi.date().iso().optional().allow(null),
    phone: Joi.string().optional().allow(null),
    address: Joi.string().optional().allow(null),
    advance_directive: Joi.string().optional().allow(null),
    preferred_hospital: Joi.string().optional().allow(null),
    hospital_address: Joi.string().optional().allow(null),
    hospital_phone: Joi.string().optional().allow(null),
    pharmacy_name: Joi.string().optional().allow(null),
    pharmacy_address: Joi.string().optional().allow(null),
    pharmacy_phone: Joi.string().optional().allow(null),
    pharmacy_fax: Joi.string().optional().allow(null),
    code_status: Joi.string().optional().allow(null),
    ssn: Joi.string().optional().allow(null),
  }),
  emergency_contact: Joi.object({
    first_name: Joi.string().optional().allow(null),
    last_name: Joi.string().optional().allow(null),
    relationship: Joi.string().optional().allow(null),
    phone: Joi.string().optional().allow(null),
    email: Joi.string().optional().allow(null),
    address: Joi.string().optional().allow(null),
  }).optional(),
  medications: Joi.array().items(
    Joi.object({
      id: Joi.string().uuid().optional(),
      medication_name: Joi.string().optional().allow(null),
      dosage: Joi.string().optional().allow(null),
      purpose: Joi.string().optional().allow(null),
      prescribing_doctor: Joi.string().optional().allow(null),
      frequency: Joi.string().optional().allow(null),
      start_date: Joi.date().iso().optional().allow(null),
      end_date: Joi.date().iso().optional().allow(null),
      refill_due: Joi.date().iso().optional().allow(null),
    })
  ),
  healthcare_providers: Joi.array().items(
    Joi.object({
      id: Joi.string().uuid().optional(),
      provider_type: Joi.string().optional().allow(null),
      provider_name: Joi.string().optional().allow(null),
      specialty: Joi.string().optional().allow(null),
      phone: Joi.string().optional().allow(null),
      email: Joi.string().optional().allow(null),
      address: Joi.string().optional().allow(null),
      last_visit: Joi.date().iso().optional().allow(null),
      next_visit: Joi.date().iso().optional().allow(null),
    })
  ),
  medical_info: Joi.object({
    allergies: Joi.string().optional().allow(null),
    diagnoses: Joi.string().optional().allow(null),
    surgical_history: Joi.string().optional().allow(null),
    cognitive_status: Joi.string().optional().allow(null),
    last_cognitive_screening: Joi.date().iso().optional().allow(null),
    cognitive_score: Joi.string().optional().allow(null),
  }),
  short_form: Joi.object({
    insurance: Joi.string().optional().allow(null),
    medicare: Joi.string().optional().allow(null),
    group_number: Joi.string().optional().allow(null),
    id_number: Joi.string().optional().allow(null),
    mpoa: Joi.string().optional().allow(null),
    mpoa_phone: Joi.string().optional().allow(null),
    mpoa_address: Joi.string().optional().allow(null),
    dpoa: Joi.string().optional().allow(null),
    dpoa_phone: Joi.string().optional().allow(null),
    dpoa_address: Joi.string().optional().allow(null),
  }),
});
